changed

diff --git a/.github/workflows/create-infra.yaml b/.github/workflows/create-infra.yaml
--- a/.github/workflows/create-infra.yaml
+++ b/.github/workflows/create-infra.yaml
@@ -91,3 +91,36 @@ jobs:
           echo 'locals {' > SSH_Key_name.tf
           echo '  key_name = var.key_name' >> SSH_Key_name.tf
           echo '}' >> SSH_Key_name.tf
+
+      - name: change folder
+        run: cd ./infra
+
+      - name: Terraform init
+        run: terraform init -upgrade
+      
+      - name: Terraform plan
+        id: plan
+        run: |
+          set +e
+          terraform plan -detailed-exitcode -input=false -out=tfplan
+          exit_code=$?
+          set -e
+          if [ $exit_code -eq 2 ]; then
+            echo "There are pending changes."
+            exit 0
+          elif [ $exit_code -eq 0 ]; then
+            echo "No changes detected in the Terraform plan."
+            exit 0
+          else
+            echo "Terraform plan failed."
+            exit 1
+          fi
+
+      - name: Notify failure
+        if: ${{ failure() }}
+        run: |
+          echo "Pipeline failed."
+
+      - name: Terraform apply
+        if: steps.plan.outcome == 'success'
+        run: terraform apply -auto-approve tfplan
